### ISSUE TITLE
Bypass the disabling of Appearance Settings while running a modded ROM in Mario 64 Movie Maker

### ISSUE THREAD

**Issue by ghost** [GlitchyPSIX/M64MM2#17]
Pretty sure I have mentioned this issue before, but to explain, Mario 64 Movie Maker does a simple check to see if the ROM loaded in Project64 is using a vanilla player model.

If it returns as a modded ROM, access to Appearance Settings is disabled by showing an error message instead of the expected window.

![image](https://user-images.githubusercontent.com/46357991/61337329-f7110700-a802-11e9-9afc-6290ce3615c3.png)

However, this does not check if the Appearance Settings window _is_ _even_ open. In this case, you could just launch a vanilla ROM, open the Appearance Settings then switch to a modded ROM. As it doesn't double-check for any instances of the Appearance Settings form, you can use the settings along with all its features (and of course break the model).

![image](https://user-images.githubusercontent.com/46357991/61337473-77d00300-a803-11e9-9111-6491ab1187ff.png)

I think a solution to this would just be disabling every feature of the Appearance Settings rather than just deny access to it completely. The user would still access it but won't be able to do anything. Then again, that depends on what you might think works out for this.

**Comment by GlitchyPSIX** [comment]
fixed in commit eec812a
